"""
Python bindings for pyFIDESlib (fideslib 2.0 CPU+GPU CKKS API)
"""
from __future__ import annotations
import collections.abc
import typing
__all__: list[str] = ['ADVANCEDSHE', 'BINARY', 'CCParams', 'Ciphertext', 'CiphertextMatrixGPU', 'CryptoContext', 'DecryptResult', 'FHE', 'FIXEDAUTO', 'FIXEDMANUAL', 'FLEXIBLEAUTO', 'FLEXIBLEAUTOEXT', 'GAUSSIAN', 'HEStd_128_classic', 'HEStd_128_quantum', 'HEStd_192_classic', 'HEStd_192_quantum', 'HEStd_256_classic', 'HEStd_256_quantum', 'HEStd_NotSet', 'HYBRID', 'JSON', 'KEYSWITCH', 'KeyPair', 'KeySwitchTechnique', 'LEVELEDSHE', 'MULTIPARTY', 'MatMulPrecompGPU', 'PKE', 'PKESchemeFeature', 'PRE', 'Plaintext', 'PlaintextMatrixGPU', 'PrivateKey', 'PublicKey', 'SCHEMESWITCH', 'SPARSE_ENCAPSULATED', 'SPARSE_TERNARY', 'ScalingTechnique', 'SecretKeyDist', 'SecurityLevel', 'SerType', 'UNIFORM_TERNARY', 'ccmm_gpu', 'ccmm_gpu_custom_bias_proto', 'ccmm_gpu_custom_proto', 'deserialize_crypto_context', 'deserialize_private_key', 'deserialize_public_key', 'gen_crypto_context', 'generate_matmul_rotation_indices_gpu', 'get_matmul_precomp_gpu', 'pcmm_gpu', 'pcmm_gpu_custom_bias_proto', 'pcmm_gpu_custom_proto', 'pcmm_gpu_masked', 'serialize_crypto_context', 'serialize_private_key', 'serialize_public_key']
class CCParams:
    def __init__(self) -> None:
        ...
    def get_batch_size(self) -> int:
        ...
    def get_multiplicative_depth(self) -> int:
        ...
    def get_secret_key_dist(self) -> SecretKeyDist:
        ...
    def set_batch_size(self, size: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def set_ciphertext_autoload(self, autoload: bool) -> None:
        ...
    def set_devices(self, devices: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex] = [0]) -> None:
        ...
    def set_digit_size(self, size: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def set_first_mod_size(self, size: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def set_key_switch_technique(self, tech: KeySwitchTechnique) -> None:
        ...
    def set_multiplicative_depth(self, depth: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def set_num_large_digits(self, num_digits: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def set_plaintext_autoload(self, autoload: bool) -> None:
        ...
    def set_ring_dim(self, dim: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def set_scaling_mod_size(self, size: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def set_scaling_technique(self, tech: ScalingTechnique) -> None:
        ...
    def set_secret_key_dist(self, dist: SecretKeyDist) -> None:
        ...
    def set_security_level(self, level: SecurityLevel) -> None:
        ...
class Ciphertext:
    def clone(self) -> Ciphertext:
        ...
    def get_level(self) -> int:
        ...
    def get_noise_scale_deg(self) -> int:
        ...
    def set_level(self, level: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def set_slots(self, slots: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def loaded(self) -> bool:
        ...
class CiphertextMatrixGPU:
    def __init__(self, cc: CryptoContext, rows: list) -> None:
        ...
    def __len__(self) -> int:
        ...
    def to_list(self, cc: CryptoContext) -> list:
        ...
class CryptoContext:
    @staticmethod
    def serialize_eval_automorphism_key(path: str) -> bool:
        ...
    @staticmethod
    def serialize_eval_mult_key(path: str) -> bool:
        ...
    @staticmethod
    def set_level(ct: Ciphertext, level: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def accumulate_sum(self, ct: Ciphertext, slots: typing.SupportsInt | typing.SupportsIndex, stride: typing.SupportsInt | typing.SupportsIndex = 1) -> Ciphertext:
        ...
    def decrypt(self, secret_key: PrivateKey, ct: Ciphertext) -> Plaintext:
        ...
    def deserialize_eval_automorphism_key(self, path: str) -> bool:
        ...
    def deserialize_eval_mult_key(self, path: str) -> bool:
        ...
    def enable(self, feature: PKESchemeFeature) -> None:
        ...
    def enable_mask(self, mask: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def encrypt(self, public_key: PublicKey, pt: Plaintext) -> Ciphertext:
        ...
    def encrypt_sk(self, secret_key: PrivateKey, pt: Plaintext) -> Ciphertext:
        ...
    def eval_add(self, ct1: Ciphertext, ct2: Ciphertext) -> Ciphertext:
        ...
    def eval_add_pt(self, ct: Ciphertext, pt: Plaintext) -> Ciphertext:
        ...
    def eval_add_scalar(self, ct: Ciphertext, scalar: typing.SupportsFloat | typing.SupportsIndex) -> Ciphertext:
        ...
    def eval_bootstrap(self, ct: Ciphertext, num_iterations: typing.SupportsInt | typing.SupportsIndex = 1, precision: typing.SupportsInt | typing.SupportsIndex = 0) -> Ciphertext:
        ...
    def eval_bootstrap_key_gen(self, sk: PrivateKey, slots: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def eval_bootstrap_setup(self, level_budget: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], dim1: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], slots: typing.SupportsInt | typing.SupportsIndex, correction_factor: typing.SupportsInt | typing.SupportsIndex = 0) -> None:
        ...
    def eval_mult(self, ct1: Ciphertext, ct2: Ciphertext) -> Ciphertext:
        ...
    def eval_mult_key_gen(self, sk: PrivateKey) -> None:
        ...
    def eval_mult_pt(self, ct: Ciphertext, pt: Plaintext) -> Ciphertext:
        ...
    def eval_mult_scalar(self, ct: Ciphertext, scalar: typing.SupportsFloat | typing.SupportsIndex) -> Ciphertext:
        ...
    def eval_negate(self, ct: Ciphertext) -> Ciphertext:
        ...
    def eval_rotate(self, ct: Ciphertext, index: typing.SupportsInt | typing.SupportsIndex) -> Ciphertext:
        ...
    def eval_rotate_key_gen(self, sk: PrivateKey, steps: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None:
        ...
    def eval_square(self, ct: Ciphertext) -> Ciphertext:
        ...
    def eval_sub(self, ct1: Ciphertext, ct2: Ciphertext) -> Ciphertext:
        ...
    def eval_sub_pt(self, ct: Ciphertext, pt: Plaintext) -> Ciphertext:
        ...
    def eval_sub_scalar(self, ct: Ciphertext, scalar: typing.SupportsFloat | typing.SupportsIndex) -> Ciphertext:
        ...
    def get_cyclotomic_order(self) -> int:
        ...
    def get_pre_scale_factor(self, slots: typing.SupportsInt | typing.SupportsIndex) -> float:
        ...
    def get_ring_dimension(self) -> int:
        ...
    def key_gen(self) -> KeyPair:
        ...
    def load_ciphertext(self, ct: Ciphertext) -> None:
        ...
    def load_context(self, public_key: PublicKey) -> None:
        ...
    def load_plaintext(self, pt: Plaintext) -> None:
        ...
    def make_ckks_packed_plaintext(self, value: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex], noise_scale_deg: typing.SupportsInt | typing.SupportsIndex = 1, level: typing.SupportsInt | typing.SupportsIndex = 0, slots: typing.SupportsInt | typing.SupportsIndex = 0) -> Plaintext:
        ...
    def make_ckks_packed_plaintext_complex(self, value: collections.abc.Sequence[typing.SupportsComplex | typing.SupportsFloat | typing.SupportsIndex], noise_scale_deg: typing.SupportsInt | typing.SupportsIndex = 1, level: typing.SupportsInt | typing.SupportsIndex = 0, slots: typing.SupportsInt | typing.SupportsIndex = 0) -> Plaintext:
        ...
    def rescale(self, ct: Ciphertext) -> Ciphertext:
        ...
    def rescale_in_place(self, ct: Ciphertext) -> None:
        ...
    def set_auto_load_ciphertexts(self, autoload: bool) -> None:
        ...
    def set_auto_load_plaintexts(self, autoload: bool) -> None:
        ...
    def set_devices(self, devices: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None:
        ...
    def synchronize(self) -> None:
        ...
class DecryptResult:
    @property
    def is_valid(self) -> bool:
        ...
    @property
    def message_length(self) -> int:
        ...
class KeyPair:
    public_key: PublicKey
    secret_key: PrivateKey
class KeySwitchTechnique:
    """
    Members:
    
      HYBRID
    """
    HYBRID: typing.ClassVar[KeySwitchTechnique]  # value = <KeySwitchTechnique.HYBRID: 2>
    __members__: typing.ClassVar[dict[str, KeySwitchTechnique]]  # value = {'HYBRID': <KeySwitchTechnique.HYBRID: 2>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class MatMulPrecompGPU:
    @property
    def bstep(self) -> int:
        ...
    @property
    def row_size(self) -> int:
        ...
class PKESchemeFeature:
    """
    Members:
    
      PKE
    
      KEYSWITCH
    
      PRE
    
      LEVELEDSHE
    
      ADVANCEDSHE
    
      MULTIPARTY
    
      FHE
    
      SCHEMESWITCH
    """
    ADVANCEDSHE: typing.ClassVar[PKESchemeFeature]  # value = <PKESchemeFeature.ADVANCEDSHE: 16>
    FHE: typing.ClassVar[PKESchemeFeature]  # value = <PKESchemeFeature.FHE: 64>
    KEYSWITCH: typing.ClassVar[PKESchemeFeature]  # value = <PKESchemeFeature.KEYSWITCH: 2>
    LEVELEDSHE: typing.ClassVar[PKESchemeFeature]  # value = <PKESchemeFeature.LEVELEDSHE: 8>
    MULTIPARTY: typing.ClassVar[PKESchemeFeature]  # value = <PKESchemeFeature.MULTIPARTY: 32>
    PKE: typing.ClassVar[PKESchemeFeature]  # value = <PKESchemeFeature.PKE: 1>
    PRE: typing.ClassVar[PKESchemeFeature]  # value = <PKESchemeFeature.PRE: 4>
    SCHEMESWITCH: typing.ClassVar[PKESchemeFeature]  # value = <PKESchemeFeature.SCHEMESWITCH: 128>
    __members__: typing.ClassVar[dict[str, PKESchemeFeature]]  # value = {'PKE': <PKESchemeFeature.PKE: 1>, 'KEYSWITCH': <PKESchemeFeature.KEYSWITCH: 2>, 'PRE': <PKESchemeFeature.PRE: 4>, 'LEVELEDSHE': <PKESchemeFeature.LEVELEDSHE: 8>, 'ADVANCEDSHE': <PKESchemeFeature.ADVANCEDSHE: 16>, 'MULTIPARTY': <PKESchemeFeature.MULTIPARTY: 32>, 'FHE': <PKESchemeFeature.FHE: 64>, 'SCHEMESWITCH': <PKESchemeFeature.SCHEMESWITCH: 128>}
    def __and__(self, other: typing.Any) -> typing.Any:
        ...
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __ge__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __gt__(self, other: typing.Any) -> bool:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __invert__(self) -> typing.Any:
        ...
    def __le__(self, other: typing.Any) -> bool:
        ...
    def __lt__(self, other: typing.Any) -> bool:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __or__(self, other: typing.Any) -> typing.Any:
        ...
    def __rand__(self, other: typing.Any) -> typing.Any:
        ...
    def __repr__(self) -> str:
        ...
    def __ror__(self, other: typing.Any) -> typing.Any:
        ...
    def __rxor__(self, other: typing.Any) -> typing.Any:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    def __xor__(self, other: typing.Any) -> typing.Any:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class Plaintext:
    def __repr__(self) -> str:
        ...
    def get_ckks_packed_value(self) -> list[complex]:
        ...
    def get_level(self) -> int:
        ...
    def get_log_precision(self) -> float:
        ...
    def get_real_packed_value(self) -> list[float]:
        ...
    def set_length(self, length: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def set_slots(self, slots: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class PlaintextMatrixGPU:
    def __init__(self, cc: CryptoContext, rows: list) -> None:
        ...
    def __len__(self) -> int:
        ...
class PrivateKey:
    pass
class PublicKey:
    pass
class ScalingTechnique:
    """
    Members:
    
      FIXEDMANUAL
    
      FIXEDAUTO
    
      FLEXIBLEAUTO
    
      FLEXIBLEAUTOEXT
    """
    FIXEDAUTO: typing.ClassVar[ScalingTechnique]  # value = <ScalingTechnique.FIXEDAUTO: 1>
    FIXEDMANUAL: typing.ClassVar[ScalingTechnique]  # value = <ScalingTechnique.FIXEDMANUAL: 0>
    FLEXIBLEAUTO: typing.ClassVar[ScalingTechnique]  # value = <ScalingTechnique.FLEXIBLEAUTO: 2>
    FLEXIBLEAUTOEXT: typing.ClassVar[ScalingTechnique]  # value = <ScalingTechnique.FLEXIBLEAUTOEXT: 3>
    __members__: typing.ClassVar[dict[str, ScalingTechnique]]  # value = {'FIXEDMANUAL': <ScalingTechnique.FIXEDMANUAL: 0>, 'FIXEDAUTO': <ScalingTechnique.FIXEDAUTO: 1>, 'FLEXIBLEAUTO': <ScalingTechnique.FLEXIBLEAUTO: 2>, 'FLEXIBLEAUTOEXT': <ScalingTechnique.FLEXIBLEAUTOEXT: 3>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class SecretKeyDist:
    """
    Members:
    
      GAUSSIAN
    
      UNIFORM_TERNARY
    
      SPARSE_TERNARY
    
      SPARSE_ENCAPSULATED
    """
    GAUSSIAN: typing.ClassVar[SecretKeyDist]  # value = <SecretKeyDist.GAUSSIAN: 0>
    SPARSE_ENCAPSULATED: typing.ClassVar[SecretKeyDist]  # value = <SecretKeyDist.SPARSE_ENCAPSULATED: 3>
    SPARSE_TERNARY: typing.ClassVar[SecretKeyDist]  # value = <SecretKeyDist.SPARSE_TERNARY: 2>
    UNIFORM_TERNARY: typing.ClassVar[SecretKeyDist]  # value = <SecretKeyDist.UNIFORM_TERNARY: 1>
    __members__: typing.ClassVar[dict[str, SecretKeyDist]]  # value = {'GAUSSIAN': <SecretKeyDist.GAUSSIAN: 0>, 'UNIFORM_TERNARY': <SecretKeyDist.UNIFORM_TERNARY: 1>, 'SPARSE_TERNARY': <SecretKeyDist.SPARSE_TERNARY: 2>, 'SPARSE_ENCAPSULATED': <SecretKeyDist.SPARSE_ENCAPSULATED: 3>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class SecurityLevel:
    """
    Members:
    
      HEStd_128_classic
    
      HEStd_192_classic
    
      HEStd_256_classic
    
      HEStd_128_quantum
    
      HEStd_192_quantum
    
      HEStd_256_quantum
    
      HEStd_NotSet
    """
    HEStd_128_classic: typing.ClassVar[SecurityLevel]  # value = <SecurityLevel.HEStd_128_classic: 0>
    HEStd_128_quantum: typing.ClassVar[SecurityLevel]  # value = <SecurityLevel.HEStd_128_quantum: 3>
    HEStd_192_classic: typing.ClassVar[SecurityLevel]  # value = <SecurityLevel.HEStd_192_classic: 1>
    HEStd_192_quantum: typing.ClassVar[SecurityLevel]  # value = <SecurityLevel.HEStd_192_quantum: 4>
    HEStd_256_classic: typing.ClassVar[SecurityLevel]  # value = <SecurityLevel.HEStd_256_classic: 2>
    HEStd_256_quantum: typing.ClassVar[SecurityLevel]  # value = <SecurityLevel.HEStd_256_quantum: 5>
    HEStd_NotSet: typing.ClassVar[SecurityLevel]  # value = <SecurityLevel.HEStd_NotSet: 6>
    __members__: typing.ClassVar[dict[str, SecurityLevel]]  # value = {'HEStd_128_classic': <SecurityLevel.HEStd_128_classic: 0>, 'HEStd_192_classic': <SecurityLevel.HEStd_192_classic: 1>, 'HEStd_256_classic': <SecurityLevel.HEStd_256_classic: 2>, 'HEStd_128_quantum': <SecurityLevel.HEStd_128_quantum: 3>, 'HEStd_192_quantum': <SecurityLevel.HEStd_192_quantum: 4>, 'HEStd_256_quantum': <SecurityLevel.HEStd_256_quantum: 5>, 'HEStd_NotSet': <SecurityLevel.HEStd_NotSet: 6>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class SerType:
    """
    Members:
    
      BINARY
    
      JSON
    """
    BINARY: typing.ClassVar[SerType]  # value = <SerType.BINARY: 0>
    JSON: typing.ClassVar[SerType]  # value = <SerType.JSON: 1>
    __members__: typing.ClassVar[dict[str, SerType]]  # value = {'BINARY': <SerType.BINARY: 0>, 'JSON': <SerType.JSON: 1>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
def ccmm_gpu(cc: CryptoContext, mat1: CiphertextMatrixGPU, mat2: CiphertextMatrixGPU, row_size: typing.SupportsInt | typing.SupportsIndex, precomp: MatMulPrecompGPU) -> CiphertextMatrixGPU:
    ...
def ccmm_gpu_custom_bias_proto(cc: CryptoContext, mat1: CiphertextMatrixGPU, mat2: CiphertextMatrixGPU, bias: PlaintextMatrixGPU, row_size: typing.SupportsInt | typing.SupportsIndex, max_slots: typing.SupportsInt | typing.SupportsIndex, rotate_sign: typing.SupportsInt | typing.SupportsIndex = 1) -> CiphertextMatrixGPU:
    ...
def ccmm_gpu_custom_proto(cc: CryptoContext, mat1: CiphertextMatrixGPU, mat2: CiphertextMatrixGPU, row_size: typing.SupportsInt | typing.SupportsIndex, max_slots: typing.SupportsInt | typing.SupportsIndex, rotate_sign: typing.SupportsInt | typing.SupportsIndex = 1) -> CiphertextMatrixGPU:
    ...
def pcmm_gpu_custom_bias_proto(cc: CryptoContext, mat1: CiphertextMatrixGPU, mat2: PlaintextMatrixGPU, bias: PlaintextMatrixGPU, row_size: typing.SupportsInt | typing.SupportsIndex, max_slots: typing.SupportsInt | typing.SupportsIndex, rotate_sign: typing.SupportsInt | typing.SupportsIndex = 1) -> CiphertextMatrixGPU:
    ...
def pcmm_gpu_custom_proto(cc: CryptoContext, mat1: CiphertextMatrixGPU, mat2: PlaintextMatrixGPU, row_size: typing.SupportsInt | typing.SupportsIndex, max_slots: typing.SupportsInt | typing.SupportsIndex, rotate_sign: typing.SupportsInt | typing.SupportsIndex = 1) -> CiphertextMatrixGPU:
    ...
def deserialize_crypto_context(path: str, cc: CryptoContext) -> bool:
    ...
def deserialize_private_key(path: str, sk: PrivateKey) -> bool:
    ...
def deserialize_public_key(path: str, pk: PublicKey) -> bool:
    ...
def gen_crypto_context(params: CCParams) -> CryptoContext:
    """
    Create a CryptoContext from CCParams.
    """
def generate_matmul_rotation_indices_gpu(row_size: typing.SupportsInt | typing.SupportsIndex, bstep: typing.SupportsInt | typing.SupportsIndex, col_size: typing.SupportsInt | typing.SupportsIndex = 0) -> list[int]:
    ...
def get_matmul_precomp_gpu(cc: CryptoContext, row_size: typing.SupportsInt | typing.SupportsIndex, bstep: typing.SupportsInt | typing.SupportsIndex, level_cp: typing.SupportsInt | typing.SupportsIndex, level_cc: typing.SupportsInt | typing.SupportsIndex, fuse_boot_prescale: bool = False, slots: typing.SupportsInt | typing.SupportsIndex = 0) -> MatMulPrecompGPU:
    ...
def get_matmul_precomp_single_level_gpu(cc: CryptoContext, row_size: typing.SupportsInt | typing.SupportsIndex, bstep: typing.SupportsInt | typing.SupportsIndex, level: typing.SupportsInt | typing.SupportsIndex, fuse_boot_prescale: bool = False, slots: typing.SupportsInt | typing.SupportsIndex = 0) -> MatMulPrecompGPU:
    ...
def pcmm_gpu(cc: CryptoContext, mat1: CiphertextMatrixGPU, mat2: PlaintextMatrixGPU, row_size: typing.SupportsInt | typing.SupportsIndex, precomp: MatMulPrecompGPU, bias: PlaintextMatrixGPU) -> CiphertextMatrixGPU:
    ...
def pcmm_gpu_masked(cc: CryptoContext, mat1: CiphertextMatrixGPU, mat2: PlaintextMatrixGPU, row_size: typing.SupportsInt | typing.SupportsIndex, precomp: MatMulPrecompGPU, bias: PlaintextMatrixGPU, mask_row: Plaintext) -> CiphertextMatrixGPU:
    ...
def serialize_crypto_context(path: str, cc: CryptoContext) -> bool:
    ...
def serialize_private_key(path: str, sk: PrivateKey) -> bool:
    ...
def serialize_public_key(path: str, pk: PublicKey) -> bool:
    ...
ADVANCEDSHE: PKESchemeFeature  # value = <PKESchemeFeature.ADVANCEDSHE: 16>
BINARY: SerType  # value = <SerType.BINARY: 0>
FHE: PKESchemeFeature  # value = <PKESchemeFeature.FHE: 64>
FIXEDAUTO: ScalingTechnique  # value = <ScalingTechnique.FIXEDAUTO: 1>
FIXEDMANUAL: ScalingTechnique  # value = <ScalingTechnique.FIXEDMANUAL: 0>
FLEXIBLEAUTO: ScalingTechnique  # value = <ScalingTechnique.FLEXIBLEAUTO: 2>
FLEXIBLEAUTOEXT: ScalingTechnique  # value = <ScalingTechnique.FLEXIBLEAUTOEXT: 3>
GAUSSIAN: SecretKeyDist  # value = <SecretKeyDist.GAUSSIAN: 0>
HEStd_128_classic: SecurityLevel  # value = <SecurityLevel.HEStd_128_classic: 0>
HEStd_128_quantum: SecurityLevel  # value = <SecurityLevel.HEStd_128_quantum: 3>
HEStd_192_classic: SecurityLevel  # value = <SecurityLevel.HEStd_192_classic: 1>
HEStd_192_quantum: SecurityLevel  # value = <SecurityLevel.HEStd_192_quantum: 4>
HEStd_256_classic: SecurityLevel  # value = <SecurityLevel.HEStd_256_classic: 2>
HEStd_256_quantum: SecurityLevel  # value = <SecurityLevel.HEStd_256_quantum: 5>
HEStd_NotSet: SecurityLevel  # value = <SecurityLevel.HEStd_NotSet: 6>
HYBRID: KeySwitchTechnique  # value = <KeySwitchTechnique.HYBRID: 2>
JSON: SerType  # value = <SerType.JSON: 1>
KEYSWITCH: PKESchemeFeature  # value = <PKESchemeFeature.KEYSWITCH: 2>
LEVELEDSHE: PKESchemeFeature  # value = <PKESchemeFeature.LEVELEDSHE: 8>
MULTIPARTY: PKESchemeFeature  # value = <PKESchemeFeature.MULTIPARTY: 32>
PKE: PKESchemeFeature  # value = <PKESchemeFeature.PKE: 1>
PRE: PKESchemeFeature  # value = <PKESchemeFeature.PRE: 4>
SCHEMESWITCH: PKESchemeFeature  # value = <PKESchemeFeature.SCHEMESWITCH: 128>
SPARSE_ENCAPSULATED: SecretKeyDist  # value = <SecretKeyDist.SPARSE_ENCAPSULATED: 3>
SPARSE_TERNARY: SecretKeyDist  # value = <SecretKeyDist.SPARSE_TERNARY: 2>
UNIFORM_TERNARY: SecretKeyDist  # value = <SecretKeyDist.UNIFORM_TERNARY: 1>
